version: "3.8"
services:
  api_uabi:
    build: .
    ports:
      - 3434:3434
    environment:
      - PORT=3434
      - HOST=0.0.0.0
      - NODE_ENV=development
      - APP_KEY=7PzPCIuy_0fMnG_UQCITMXQt7-nq6CgQ
      - DRIVE_DISK=local
      - DB_CONNECTION=pg
      - PG_USER=devops
      - PG_HOST=localhost
      - PG_DB_NAME=dbuabi
      - PG_PASSWORD=My4w350m3PWD*
      - PG_PORT=5432

volumes:
  data:
